
version: '3.9'
services:


  backend:
    build:
      context: ./vvv-site-backend/
      dockerfile: Dockerfile
      target: prod
    container_name: express-api
    ports:
      - "4000:4000"
    networks:
      - app-network
    command: npm run start

  frontend:
    build:
      context: ./vvv-site-frontend/
      dockerfile: Dockerfile
      target: prod
    container_name: next-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:4000
    networks:
      - app-network
    command: npm run start


networks:
  app-network:
    driver: bridge
